# Generated by Django 4.1.7 on 2023-05-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='appdate',
            field=models.CharField(choices=[('8', '8:00AM'), ('9', '9:00AM'), ('10', '10:00AM'), ('11', '11:00AM'), ('12', '12:00PM'), ('1', '1:00PM'), ('2', '2:00PM'), ('3', '3:00PM'), ('4', '4:00PM'), ('5', '5:00PM')], default='------', max_length=20),
        ),
    ]
