# Generated by Django 4.1.7 on 2023-05-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_appdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='appdate',
        ),
        migrations.AddField(
            model_name='student',
            name='apptime',
            field=models.CharField(choices=[('8', '8:00AM'), ('9', '9:00AM'), ('10', '10:00AM'), ('11', '11:00AM'), ('12', '12:00PM'), ('1', '1:00PM'), ('2', '2:00PM'), ('3', '3:00PM'), ('4', '4:00PM'), ('5', '5:00PM')], default='8:00AM', max_length=20),
        ),
    ]
