# Generated by Django 4.1.7 on 2023-05-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_student_appdate_student_apptime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='region',
        ),
        migrations.AlterField(
            model_name='student',
            name='apptime',
            field=models.CharField(choices=[('8:00AM', '8:00AM'), ('9:00AM', '9:00AM'), ('10:00AM', '10:00AM'), ('11:00AM', '11:00AM'), ('12:00PM', '12:00PM'), ('1:00PM', '1:00PM'), ('2:00PM', '2:00PM'), ('3:00PM', '3:00PM'), ('4:00PM', '4:00PM'), ('5:00PM', '5:00PM')], max_length=20),
        ),
    ]
