# Generated by Django 4.1.7 on 2023-05-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_barangay_student_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='appdate',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='---', max_length=20),
        ),
    ]
