# Generated by Django 4.1.7 on 2023-05-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_student_status_alter_student_appdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
