# Generated by Django 4.2.1 on 2023-05-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_applicant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='applicant_pics/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
