# Generated by Django 4.2.1 on 2023-05-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_applicant_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='pic',
            field=models.ImageField(null=True, upload_to='myapp/applicant_pics/covers'),
        ),
    ]
